---

- name: Ensure download directory is present
  file:
    path: "{{ download_dir }}"
    state: directory

- name: Download Nagios Plugins
  command: wget -O "{{ download_dir }}/nagios-plugins-release-{{ nagios_plugins_version }}.tar.gz" "https://nagios-plugins.org/download/nagios-plugins-{{ nagios_plugins_version }}.tar.gz"

- name: Unpack Nagios plugin source
  unarchive:
    src: "{{ download_dir }}/nagios-plugins-release-{{ nagios_plugins_version }}.tar.gz"
    dest: "{{ download_dir }}/"
    remote_src: true

- name: Configure NRPE
  command: "./configure --with-nagios-user={{ nrpe_user }} --with-nagios-group={{ nrpe_group }}"
  args:
    chdir: "{{ download_dir }}/nagios-plugins-{{ nagios_plugins_version }}"
    creates: "{{ download_dir }}/nagios-plugins-{{ nagios_plugins_version }}/Makefile"

- name: Make for plugins
  command: make
  args:
    chdir: "{{ download_dir }}/nagios-plugins-{{ nagios_plugins_version }}"

- name: Make NRPE
  command: make install
  args:
    chdir: "{{ download_dir }}/nagios-plugins-{{ nagios_plugins_version }}"
