---
- name: Create Host Directory on Nagios Server
  #delegate_to: "{{ item.name }}"
  file:
    path:   "{{ nagios_host_path }}"
    state:  directory
    force:  yes
    owner:  "{{ nagios_server_user }}"
    group:  "{{ nagios_server_group }}"
    mode:   '0755'
    seuser: system_u
    serole: object_r
    setype: nrpe_etc_t
  when: inventory_hostname in groups['nserver']

- name: Service Definitions on Nagios Server
  #delegate_to: "{{ item.name }}"
  template:
    src:    "{{ item.src }}.j2"
    dest:   "{{ nagios_objects_path }}/{{ item.dest }}"
    force:  yes
    owner:  "{{ nagios_server_user }}"
    group:  "{{ nagios_server_group }}"
    mode:   '0644'
  with_items:
    - { src: "Nagios_server/groups/basic.cfg",         dest: "ansible-shards/0-groups-basic.cfg" }
    - { src: "Nagios_server/hosts/templates.cfg",      dest: "hosts/{{ ansible_hostname }}/templates.cfg" }
    - { src: "Nagios_server/hosts/host.cfg",           dest: "hosts/{{ ansible_hostname }}/host.cfg" }
    - { src: "Nagios_server/hosts/service-basic.cfg", dest: "hosts/{{ ansible_hostname }}/service-basics.cfg" }
  when: inventory_hostname in groups['nserver']
