---

- name: Create NRPE group
  group:
    name: "{{ nrpe_group }}"
    state: present

- name: Create NRPE user
  user:
    name: "{{ nrpe_user }}"
    groups: "{{ nrpe_group }}"
    state: present

- name: add nrpe user to the sudoers to access docker daemon
  copy: 
    dest: /etc/sudoers.d/containers_monitor
    content: |
      %"{{ nrpe_user }}"  ALL=(ALL)   NOPASSWD: /usr/bin/docker