---

- name: Create NRPE group
  group:
    name: "{{ nrpe_group }}"
    state: present

- name: Create NRPE user
  user:
    name: "{{ nrpe_user }}"
    groups: "{{ nrpe_group }}"
    state: present
