---

- name: adding templates to target directories
  template:
    src:    "{{ item.src }}.j2"
    dest:   "{{ item.dest }}"
    force:  yes
    owner:  "{{ item.owner }}"
    group:  "{{ item.group }}"
    mode:   '0644'
    seuser: system_u
    serole: object_r
    setype: nrpe_etc_t
  with_items:
   - { src: 'nrpe.cfg',  dest: "{{ nrpe_etc_path }}/nrpe.cfg", owner: "{{ nrpe_user }}", group: "{{ nrpe_group }}" }
   - { src: 'basic_commands.cfg', dest: "{{ nrpe_etc_path }}/basic.cfg",  owner: "{{ nrpe_user }}", group: "{{ nrpe_group }}" }
  tags: nrpe

- name: Add aditional plugins 
  copy:
    src:    CustomPlugins/
    dest:   "{{ nrpe_nagios_path }}/"
    force:  yes
    owner:  "{{ nrpe_user }}"
    group:  "{{ nrpe_group }}"
    mode:   '0755'
    seuser: system_u
    serole: object_r
    setype: nagios_unconfined_plugin_exec_t
  tags: nrpe

- name: Set allowed_hosts in nrpe.cfg
  lineinfile:
    dest: "{{ nrpe_etc_path }}/nrpe.cfg"
    regexp: '^allowed_hosts='
    line: "allowed_hosts={% for host in nrpe_allowed_hosts %}{{ host }}{% if not loop.last %},{% endif %}{% endfor %}"

- name: Set dont_blame in nrpe.cfg
  lineinfile:
    dest: "{{ nrpe_etc_path }}/nrpe.cfg"
    regexp: '^dont_blame_nrpe='
    line: "dont_blame_nrpe={{ nrpe_dont_blame }}"
  notify: restart nrpe  

